import type { Metadata } from "next";
import { Geist, Geist_Mono,Mona_Sans,Grand_Hotel } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const hotel = Grand_Hotel( {
  weight: "400",
  variable: "--font-grand-hotel",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const mona = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`   ${hotel.variable}        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
